### ISSUE TITLE
Can't use the library on heroku

### ISSUE THREAD

**Issue by ignacioambia** [yunojuno/django-user-visit#11]
Hello, 
I installed the library with  `pip install django-user-visit` , tested it in my local environment and everything seems to work fine, but when i try to deploy my app to production with **Heroku** i get the following error : 

```
remote:        Collecting django-cors-headers==3.6.0
remote:          Downloading django_cors_headers-3.6.0-py3-none-any.whl (12 kB)
remote:        ERROR: Could not find a version that satisfies the requirement django-user-visit==0.4.1 (from -r /tmp/build_940d12d0/requirements.txt (line 4)) (from versions: none)
remote:        ERROR: _No matching distribution_ found for django-user-visit==0.4.1 (from -r /tmp/build_940d12d0/requirements.txt (line 4))
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
```

Does anyone know why Heroku can't find the package and if i can fix this ?

My packages are being installed by running the libraries indicated in my `requirements.txt` file:

```
asgiref==3.3.1
Django==3.1.5
django-cors-headers==3.6.0
django-user-visit==0.4.1
djangorestframework==3.12.2
gunicorn==20.0.4
psycopg2==2.8.6
pytz==2020.5
sqlparse==0.4.1
ua-parser==0.10.0
user-agents==2.2.0
whitenoise==5.2.0

```

What i've tried so far is to change the version to 0.4 and to not specify a version at all

**Comment by hugorodgerbrown** [comment]
I don't know of any reason why this wouldn't install for you - we run `django-user-visit` on Heroku ourselves, and v0.4.1 is available on PyPI: https://pypi.org/project/django-user-visit/#history

**Comment by ignacio-ambia-DSV** [comment]
The problem was that my computer was running python 3.8 like Heroku 3.6. Adding the `runtime.txt` file fixed my problem

**Comment by ignacioambia** [comment]
The problem was that my computer was running python 3.8 whileHeroku 3.6. Adding the `runtime.txt` file fixed my problem
