### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by hougomartim** [yunojuno/django-user-visit#13]
when i run pip install like below:
`pip install django-user-visit==0.4 `
cause this error:
`
ERROR: Could not find a version that satisfies the requirement django-user-visit==0.4 (from versions: none)                                                                                     
ERROR: No matching distribution found for django-user-visit==0.4                                │ No module
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
`

**Comment by hugorodgerbrown** [comment]
I think this will be the Python support - v0.4 supports Python 3.7+ - are you using an earlier version of Python?
