### ISSUE TITLE
Is possible to track device location as well?

### ISSUE THREAD

**Issue by agusmakmun** [yunojuno/django-user-visit#15]
**For example:**

**Location:** City, Region, Country

**Comment by hugorodgerbrown** [comment]
Hi @agusmakmun - this isn't possible directly as Django doesn't support location data of itself. We have another package, [`django-geoip2-extras`](https://github.com/yunojuno/django-geoip2-extras/tree/9dc8521eaa244f44e4849dcfcf753d91b79e40ff) which can be used to annotate requests with geolocation data, but it's not a dependency of this package, we don't have plans to do so at the current time.

**Comment by agusmakmun** [comment]
@hugorodgerbrown what about supporting it by using optional dependency, for example:

```
pip install django-user-visit[django-geoip2-extras]
```

then in your package;

```python

try:
    from geoip2_extras.middleware import GeoIP2Middleware
    OptionalGeoIP = GeoIP2Middleware
except ImportError:
    OptionalGeoIP = object


class UserVisitMiddleware(OptionalGeoIP):
    ...

    def __call__(self, request: HttpRequest) -> typing.Optional[HttpResponse]:
        if hasattr(self, "geo_data"):
            # do something
```

**Comment by hugorodgerbrown** [comment]
Yup - could do this - or even simpler just check for geoip metadata in the request. In other projects we use a catchall JSONField called `context` for this kind of ephemeral data.
