### ISSUE TITLE
How to use context field?

### ISSUE THREAD

**Issue by atanassia** [yunojuno/django-user-visit#24]
Hi, can you please describe how to use context field in my project? Can't understand how to add data into it

**Comment by hugorodgerbrown** [comment]
Hi @atanassia - if you want to add data to it you should add a function to your Django settings called 
`USER_VISIT_REQUEST_CONTEXT_EXTRACTOR` that takes `HttpRequest` as the only arg, and that returns a dict, which is stored in the context field.

e.g. this would store whether the user was a staff user:

```python
# settings.py

USER_VISIT_REQUEST_CONTEXT_EXTRACTOR = lambda r: { "is_staff": r.user.is_staff }
```

(typed on my phone, so apologies if formatting is off)

**Comment by atanassia** [comment]
thank you
