### ISSUE TITLE
Breaking release : V2

### ISSUE THREAD

**Issue by gaeldb** [yunojuno/django-user-visit#28]
Hello team,

Release 2 is breaking our deployment :
I have errors 500 like : **column "browser" of relation "user_visit_uservisit" does not exist**

This is probably because data structure changed in DB, but should be at least warned :(

Investigating...

**Comment by gaeldb** [comment]
Was stuck because :
pip always returns django-user-visit-1.1
because our python version was 3.7

**Comment by djm** [comment]
Hi @gaeldb.

Version 2 dropped support for Python 3.7 but unfortunately we forgot to list this in the CHANGELOG as a breaking change. We won't be supporting 3.7 any longer as we're on 3.11 and the time to do so doesn't make sense for us.

I will however update that CHANGELOG.. thank you!
