### ISSUE TITLE
Allow python 3.6 !

### ISSUE THREAD

**Issue by buriy** [yunojuno/django-user-visit#7]

**Comment by hugorodgerbrown** [comment]
Hi @buriy - this has come up in some of our other repos. Python 3.7 added support for PEP 563 (Postponed Evaluation of Annotations), which, although non-functional, makes type annotations easier to use. Unfortunately, supporting both 3.6 and 3.7 is very difficult if we want to use the type hinting style that future Python versions will support.

**Comment by buriy** [comment]
I don't think you need to do much (if anything at all!) in this project to support Python 3.6.
So I don't understand why you're referring to other projects, that are probably much bigger.

**Comment by hugorodgerbrown** [comment]
If you'd like to submit a pull request with the changes in, I will happily review and merge.
